services:
  mysql:
    image: mysql:8.0
    container_name: salon_mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: salon_management
      MYSQL_USER: salon_user
      MYSQL_PASSWORD: salon_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/src/main/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - salon_network
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: salon_backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/salon_management?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
      JWT_SECRET: mySecretKey123456789012345678901234567890
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - salon_network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: salon_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - salon_network
    restart: unless-stopped
    environment:
      - REACT_APP_API_URL=http://localhost:8080/api

volumes:
  mysql_data:

networks:
  salon_network:
    driver: bridge
